### ISSUE TITLE
Connect to a secure HBase (Kerberos)

### ISSUE THREAD

**Issue by fabiothomaz** [wso2-extensions/siddhi-store-hbase#14]
**Description:**
I'm trying connect Siddhi to HBase in a kerberized environment (using JAAS), without success. 
Is this supported? If not, any plans to support Kerberos?

**Suggested Labels:**
question, help wanted

**Affected Product Version:**
4.0.7

**OS, DB, other environment details and versions:**    
WSO2 Stream Processor 4.1.0, CentOS 7

**Comment by gokul** [comment]
Hi @fabiothomaz,

Thanks for reaching out. Unfortunately, the Siddhi HBase store does not support kerberized HBase environments at the moment. We do have plans to implement this, but I don't have a timeline for this. 

Best,
Gokul.
